<?php
/**
 * PagBank Payment Magento Module.
 *
 * Copyright © 2023 PagBank. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

/**
 * @var \PagBank\PaymentMagento\Block\Adminhtml\System\Config\Oauth $block
 */
?>
<div id="pagbank-type-apps" class="admin__table admin__table_apps_pagbank">
    <h1><?= $block->escapeHtml(__('Know and compare our <b>promotional plans</b>'), ['b']) ?></h1>
    <table id="pagbank-table-apps">
        <tr>
            <th class="feature"></th>
            <th class="plan"><?= $block->escapeHtml(__('Magento and Adobe Commerce - Account Profile')) ?></th>
            <th class="plan"><?= $block->escapeHtml(__('Magento and Adobe Commerce - D14')) ?></th>
            <th class="plan"><?= $block->escapeHtml(__('Magento and Adobe Commerce - D30')) ?></th>
        </tr>
        <tr>
            <td class="feature"><?= $block->escapeHtml(__('Benefits')) ?></td>
            <td>
                <ul>
                    <li><?= $block->escapeHtml(__('Ideal for those who bill above R$ 200,000')) ?></li>
                    <li><?= $block->escapeHtml(__('Customized fees and receipts')) ?></li>
                    <li>
                        <?= $block->escapeHtml(
                            __(
                                'Request your personalized proposal <a href="%1">here</a>',
                                'https://pagseguro.uol.com.br/campanhas/contato/?parceiro=aec'
                            ),
                            ['a']
                        ) ?>
                    </li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><?= $block->escapeHtml(__('Ideal for those who need greater cash flow')) ?></li>
                    <li><?= $block->escapeHtml(__('Reduced fees')) ?></li>
                </ul>
            </td>
            <td>
                <ul>
                    <li><?= $block->escapeHtml(__('Ideal for those who have greater cash flow')) ?></li>
                    <li><?= $block->escapeHtml(__('The best market rates')) ?></li>
                </ul>
            </td>
        </tr>
        <tr>
            <td class="feature"><?= $block->escapeHtml(__('Receipt Type')) ?></td>
            <td><?= $block->escapeHtml(__('As defined in your account')) ?></td>
            <td><?= $block->escapeHtml(__('Receive within 14 days')) ?></td>
            <td><?= $block->escapeHtml(__('Receive within 30 days')) ?></td>
        </tr>
        <tr>
            <td class="feature"><?= $block->escapeHtml(__('Fees*')) ?></td>
            <td><?= $block->escapeHtml(__('As defined in your account')) ?></td>
            <td>
                <?= $block->escapeHtml(__('Card:')) ?>
                <ul>
                    <li><?= $block->escapeHtml(__('With 3.97% fee.')) ?></li>
                </ul>
                <?= $block->escapeHtml(__('Pix:')) ?>
                <ul>
                    <li><?= $block->escapeHtml(__('With 0.99% fee.')) ?></li>
                    <li><?= $block->escapeHtml(__('With immediate receipt.')) ?></li>
                </ul>
                <?= $block->escapeHtml(__('Bank Slip:')) ?>
                <ul>
                <li><?= $block->escapeHtml(__('With fixed fee of R$ 2.99.')) ?></li>
                <li><?= $block->escapeHtml(__('With receipt within 2 business days.')) ?></li>
                </ul>
            </td>
            <td>
                <?= $block->escapeHtml(__('Card:')) ?>
                <ul>
                    <li><?= $block->escapeHtml(__('With 3.05% fee.')) ?></li>
                </ul>
                <?= $block->escapeHtml(__('Pix:')) ?>
                <ul>
                    <li><?= $block->escapeHtml(__('With 0.99% fee.')) ?></li>
                    <li><?= $block->escapeHtml(__('With immediate receipt.')) ?></li>
                </ul>
                <?= $block->escapeHtml(__('Bank Slip:')) ?>
                <ul>
                <li><?= $block->escapeHtml(__('With fixed fee of R$ 2.99.')) ?></li>
                <li><?= $block->escapeHtml(__('With receipt within 2 business days.')) ?></li>
                </ul>
            </td>
        </tr>
    </table>
    <p class="note">
        <?= $block->escapeHtml(
            __('* The fees advertised here may vary, please check our page for updated values.')
        ) ?>
    </p>
</div>
