<?php
/**
 * PagBank Payment Magento Module.
 *
 * Copyright © 2023 PagBank. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

/**
 * @var \PagBank\PaymentMagento\Block\Sales\Form\Pix $block
 * @see \PagBank\PaymentMagento\Block\Sales\Form\Pix
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
$qrCode = isset($specificInfo['qr_code']) ? $specificInfo['qr_code']: null;
$qrCodeImage = isset($specificInfo['qr_code_image']) ? $specificInfo['qr_code_image'] : null;
$expirationDate = isset($specificInfo['expiration_date']) ? $specificInfo['expiration_date'] : null;
$payerName = isset($specificInfo['payer_name']) ? $specificInfo['payer_name'] : null;
$payerTaxId = isset($specificInfo['payer_tax_id']) ? $specificInfo['payer_tax_id'] : null;
?>

<?php if ($specificInfo): ?>
    <dl class="payment-method">
        <dt class="title"><?= /* @noEscape */ $title ?></dt>
        <dd class="content">
            <table class="data table" style="width: 100%;">
                <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
                <tbody>
                    <?php if ($expirationDate): ?>
                        <tr>
                            <th scope="row" style="border-top: 1px solid #EFEFEF; padding: 12px 0;">
                                <?= $block->escapeHtml(__('Expiration')); ?>
                            </th>
                            <td style="border-top: 1px solid #EFEFEF; padding: 12px 0; text-align: right;">
                                <?= /* @noEscape */ $block->formatDate(
                                    $expirationDate,
                                    \IntlDateFormatter::MEDIUM,
                                    true
                                ) ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($qrCodeImage): ?>
                        <tr>
                            <th scope="row" style="border-top: 1px solid #EFEFEF; padding: 12px 0;">
                                <?= $block->escapeHtml(__('Pix Qr Code')); ?>
                            </th>
                            <td style="border-top: 1px solid #EFEFEF; padding: 12px 0; text-align: right;">
                                <img
                                    src="<?=  $block->escapeHtml($qrCodeImage) ?>" 
                                    alt="<?= /* @noEscape */ $title ?>"
                                    width="100%"
                                    style="max-width: 150px;">
                                </img>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($qrCode): ?>
                        <tr>
                            <th scope="row" style="border-top: 1px solid #EFEFEF; padding: 12px 0;">
                                <?= $block->escapeHtml(__('Pix Copy and Paste')); ?>
                            </th>
                            <td style="border-top: 1px solid #EFEFEF; padding: 12px 0; text-align: right;">
                                <textarea style="width: 100%; box-sizing: border-box;" readonly="true"><?= $block->escapeHtml($qrCode) ?></textarea>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($payerName): ?>
                        <tr>
                            <th scope="row" style="border-top: 1px solid #EFEFEF; padding: 12px 0;">
                                <?= $block->escapeHtml(__('Payer Name')); ?>
                            </th>
                            <td style="border-top: 1px solid #EFEFEF; padding: 12px 0; text-align: right;">
                                <?= $block->escapeHtml($payerName) ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                    <?php if ($payerTaxId): ?>
                        <tr>
                            <th scope="row" style="border-top: 1px solid #EFEFEF; padding: 12px 0 0;">
                                <?= $block->escapeHtml(__('Payer Tax Id')); ?>
                            </th>
                            <td style="border-top: 1px solid #EFEFEF; padding: 12px 0 0; text-align: right;">
                                <?= $block->escapeHtml($payerTaxId) ?>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </dd>
    </dl>
<?php endif;?>