
<?php
/**
 * PagBank Payment Magento Module.
 *
 * Copyright © 2023 PagBank. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

/**
 * @var PagBank\PaymentMagento\Block\Sales\Order\Success $block
 * @see PagBank\PaymentMagento\Block\Order\Success
 */

$lineCode = $block->getInfo('boleto_line_code');
$link = $block->getInfo('boleto_pdf_href');
?>
<div class="pagbank-payment-success-details boleto">

    <div class="payment-header">
        <h3 class="payment-title"><?= $block->escapeHtml(__('Payment via Bank Slip (Boleto)')) ?></h3>
        <p class="payment-subtitle"><?= $block->escapeHtml(__('Click the button below to download the boleto or copy the barcode.')) ?></p>
    </div>

    <div class="payment-content">
        <div class="payment-actions control _with-tooltip">
            <input type="text"
                id="line-code-value"
                value="<?= $block->escapeHtml($lineCode); ?>"
                class="input-text codigo-input"/> 
            <div class="toggle">
                <button class="btn copy-button copy-boleto-button" id="copy-code" 
                    data-clipboard-action="copy" 
                    data-clipboard-target="#line-code-value">
                    <?= $block->escapeHtml(__('Copy')); ?>
                </button>
            </div>
        </div>
        <div class="pagbank-payment-boleto-link">
            <a href="<?= $block->escapeUrl($block->getMediaUrl($link)); ?>"
                target="_blank"
                class="boleto-button icon-download">
                <?= $block->escapeHtml(__('Download the Boleto')) ?> 
            </a>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#copy-code": {
            "PagBank_PaymentMagento/js/clipboard-with-class": {
                "enabled": true,
                "copiedtext": "<?= /* @noEscape */ __('Copied'); ?>",
                "textBtn": "<?= /* @noEscape */ __('Copy'); ?>",
                "copiedClass": "copied",
                "copiedClassDuration": 2000
            }
        }
    }
</script>