
<?php
/**
 * PagBank Payment Magento Module.
 *
 * Copyright © 2023 PagBank. All rights reserved.
 *
 * @author    Bruno Elisei <strongrunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

/**
 * @var PagBank\PaymentMagento\Block\Sales\Order\Success $block
 * @see PagBank\PaymentMagento\Block\Order\Success
 */
$deepLink = $block->getInfo('deep_link_url');
$qrCodeImage = $block->getInfo('qr_code_url_image');
?>
<div class="pagbank-payment-success-details">
    <h3>
        <?= $block->escapeHtml(
            __('To make the payment:')
        ) ?>
    </h3>
    <div class="pagbank-payment-deep-link-url">
        <p><?= $block->escapeHtml(__('Access your PagBank account by clicking on the link:')) ?></p>
        <a href="<?= $block->escapeUrl($deepLink); ?>"
            target="_blank"
            class="action">
            <img src="<?= $block->escapeUrl(
                $block->getViewFileUrl('PagBank_PaymentMagento::images/deep-link/btn.svg')
            ) ?>"
            width="250px"
            />
        </a>
        <p>
            <?= $block->escapeHtml(
                __('You must <strong>be redirected to PagBank</strong> to complete the payment.'),
                ['strong']
            ) ?>
        </p>
    </div>
    <div class="pagbank-payment-deep-link-image">
        <ol class="pagbank-items">
            <li class="item">
                <?= $block->escapeHtml(
                    __('Open the <strong>PagBank app</strong> on your phone;'),
                    ['strong']
                ) ?>
                </li>
            <li class="item">
                <?= $block->escapeHtml(
                    __('Go to the <strong>Pix/Qr Code</strong> option;'),
                    ['strong']
                ) ?>
            </li>
            <li class="item">
                <?= $block->escapeHtml(
                    __('Select the option <strong>"Pay with Qr Code"</strong>;'),
                    ['strong']
                ) ?>
            </li>
            <li class="item">
                <?= $block->escapeHtml(
                    __('Scan the Qr Code:')
                ) ?>
            </li>
        </ol>
        <div class="qrcode-image">
            <img src="<?= $block->escapeUrl($block->getMediaUrl($qrCodeImage)); ?>"
                class="deep-link-qrcode"
                alt="<?= $block->escapeHtml(__('Pay in PagBank')) ?>">
            </img>
        </div>
        <p>
            <?= $block->escapeHtml(
                __('Atenção o Qr Code gerado <strong>só é válido para uso no aplicatico do PagBank.</strong>'),
                ['strong']
            ) ?>
        </p>
    </div>
</div>