
<?php
/**
 * PagBank Payment Magento Module.
 *
 * Copyright © 2023 PagBank. All rights reserved.
 *
 * @author    Bruno Elisei <brunoelisei@o2ti.com>
 * @license   See LICENSE for license details.
 */

/**
 * @var PagBank\PaymentMagento\Block\Sales\Order\Success $block
 * @see PagBank\PaymentMagento\Block\Order\Success
 */
$qrCode = $block->getInfo('qr_code');
$qrCodeImage = $block->getInfo('qr_code_image');
?>
<div class="pagbank-payment-success-details pix">


    <div class="payment-header">
        <h3 class="payment-title"><?= $block->escapeHtml(__('Payment via PIX')) ?></h3>
        <p class="payment-subtitle"><?= $block->escapeHtml(__('Scan the QR code or copy the code below.')) ?></p>
    </div>

    <div class="payment-content">
        <div class="qr-code-section">
            <div class="qrcode-image qr-code-container">
                <img src="<?= $block->escapeUrl($block->getMediaUrl($qrCodeImage)); ?>"
                    class="pix-qrcode"
                    alt="<?= $block->escapeHtml(__('Pix Qr Code')) ?>">
                </img>
            </div>
            <div class="payment-actions control _with-tooltip">
                <input type="text"
                    id="line-code-value"
                    value="<?= $block->escapeHtml($qrCode); ?>"
                    class="input-text qr-input"/> 
                <div class="toggle">
                    <button class="btn copy-button copy-qr-button" id="copy-code" 
                        data-clipboard-action="copy" 
                        data-clipboard-target="#line-code-value">
                        <?= $block->escapeHtml(__('Copy')); ?>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "#copy-code": {
            "PagBank_PaymentMagento/js/clipboard-with-class": {
                "enabled": true,
                "copiedtext": "<?= /* @noEscape */ __('Copied'); ?>",
                "textBtn": "<?= /* @noEscape */ __('Copy'); ?>",
                "copiedClass": "copied",
                "copiedClassDuration": 2000
            }
        }
    }
</script>